# Generated by Django 2.0.4 on 2018-04-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_auto_20171108_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreadings',
            name='ph',
            field=models.CharField(default=5.67, max_length=30),
            preserve_default=False,
        ),
    ]
