# Generated by Django 2.0.4 on 2018-05-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0018_commom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreadings',
            name='level',
        ),
    ]
