# Generated by Django 2.0.4 on 2018-05-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0019_remove_sensorreadings_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commom',
            new_name='common',
        ),
    ]
