# Generated by Django 2.0.4 on 2018-05-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0020_auto_20180503_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='common',
        ),
    ]
